M48
; DRILL file {KiCad (6.0.8)} date Fri Oct 28 18:58:49 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-28T18:58:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.78Y-3.02
X4.78Y-5.02
X6.78Y-3.02
X6.78Y-5.02
T0
M30
